# Generated by Django 4.2.1 on 2023-06-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationplan',
            name='country',
            field=models.CharField(max_length=20, null=True, verbose_name='pais'),
        ),
    ]
