# Generated by Django 4.2.1 on 2023-06-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_vacationplan_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationplan',
            name='price',
            field=models.FloatField(verbose_name='precio'),
        ),
    ]
