# Generated by Django 4.2.1 on 2023-06-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_vacationplan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='img_url',
            field=models.CharField(max_length=200, null=True, verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='vacationplan',
            name='img_url',
            field=models.CharField(max_length=200, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.CharField(max_length=200, verbose_name='url de imagen'),
        ),
    ]
