# Generated by Django 4.2.1 on 2023-06-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_alter_blog_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='vacationplan',
            name='img_url',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default.png', upload_to='destinations', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default='default.png', upload_to='destinations', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='vacationplan',
            name='image',
            field=models.ImageField(default='default.png', upload_to='destinations', verbose_name='Imagen'),
        ),
    ]
