# Generated by Django 4.2.1 on 2023-06-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_remove_blog_image_url_remove_destination_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default.png', upload_to='blogs', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='vacationplan',
            name='image',
            field=models.ImageField(default='default.png', upload_to='vacationplans', verbose_name='Imagen'),
        ),
    ]
