# Generated by Django 4.2.1 on 2023-06-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0008_alter_blog_image_alter_vacationplan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(verbose_name='fechaDePublicacion'),
        ),
    ]
